files:
  - pathtofile: /etc/group
    keywords:
      - 
    parseAll: true
    parsingLevel: server
    sanitizationKeywords:
      - mail
      
  - pathtofile: /p4/common/config/p4_%INSTANCE%.vars
    keywords:
      - export MAILTO
      - export P4USER
      - export P4MASTER_ID
    parseAll: false
    parsingLevel: instance
    sanitizationKeywords:
      - sensitive
      - secret

  - pathtofile: /etc/group
    keywords:
      - 
    parseAll: true
    parsingLevel: instance
    sanitizationKeywords:
      - polkitd

